# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: shiny-start

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install dependencies
        run: npm ci --prefix src
      - name: Compile
        run: npm run build:deploy --prefix src
      - name: Compile & Start
        run: Rscript -e 'source("dev/compile_testing.R")' &

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: src
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: src
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: src/playwright-report/
          retention-days: 30
