name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check content directory
        run: ls
        working-directory: src
      - name: Install Dependencies
        run: npm ci
        working-directory: src
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: src
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: src
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: src/playwright-report/
          retention-days: 30
s